site_name: Amelia's BrainDump.io
site_url: https://notes.ameliali.com/
theme:
  name: material
  logo: assets/notion.png
  font:
    text: Arial
  favicon: assets/notion.png
  features:
  palette:
    - scheme: default
      primary: custom
      accent: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: false
      inject_footer: false
      timezone: America/Los_Angeles

nav:
  - Home: index.md
  - SQL:
    - Index: SQL/Index.md
  - INFO441:
    - Index: INFO441/Index.md
  - INFO449:
    - Index: INFO449/Index.md

extra:
  generator: false
  cname: notes.ameliali.com

copyright: |
  &copy; 2025 Amelia Li