site_name: Amelia's BrainDump.io
site_url: https://ameliali.com/milynotes/
theme:
  name: material
  logo: assets/notion.png
  font:
    text: Arial
  favicon: assets/notion.png
  features:
  palette:
    - scheme: default
      primary: custom
      accent: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions: 
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - SQL:
    - Index: SQL/Index.md
    - Basics: SQL/Basics.md
    - JOINs: SQL/JOINS.md
  - INFO441:
    - Index: INFO441/Index.md

extra:
  generator: false

copyright: |
  &copy; 2025 Amelia Li